#!/usr/bin/env node

const program = require('commander');
const moment = require('moment');
require('moment-timezone');
const timesheet = require('./timesheet');
const tag = require('./tag');

program
    .version('0.1.0')
    .arguments('<mood> <difficulty>  [tokens...]')
    .description('run the given remote command')
    .action((mood, difficulty, tokens) => {
        const description = tokens.join(' ');
        timesheet.listAsync()
            .then((tasks) => {
                // TODO: refactor to make the get previous task logic
                //       functional.
                let previousTask = null;
                tasks.forEach((task) => {
                    let { Time } = task.fields
                    if (!previousTask) {
                        previousTask = task;
                    } else {
                        // TODO: clean up the time logic with our own time format
                        if (moment(Time) > moment(previousTask.fields.Time)) {
                            previousTask = task;
                        }
                    }
                });
                // Set the duraction of previous task
                if (previousTask) {
                    const recordId = previousTask['_rawJson']['id'];
                    const Duration = `${moment().diff(moment(previousTask.fields.Time), 'minute')} minutes`;
                    console.log( `Duration: ${Duration}` );
                    previousTask.updateFields({Duration});
                }
                return timesheet.startAsync(
                    tag.normalize(mood),
                    parseInt(difficulty, 10),
                    description,
                    previousTask && previousTask.fields.Time
                );
            })
            .then((res) => {
                const { Time } = res.fields;
                console.log( `Time: ${Time}` );
            })
            .catch((err) => {
                console.error(err);
            });
    })

program
    .parse(process.argv);
